# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:3306)/test_go_frame"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true


# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:root:123456@tcp(127.0.0.1:3306)/test_go_frame"
        tables = "user"